# This file was generated by GoReleaser. DO NOT EDIT.
cask "spelling-gopher" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "16af3b5520290c739d185ae7417bca63570740210968fbbb13a176bac5a6f452"
      url "https://github.com/Perchinka/SpellingGopher/releases/download/v#{version}/spelling-gopher_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8ccfafcca4330e8f7d8d73605b4f14971434b572df7849ec250a2707606c401e"
      url "https://github.com/Perchinka/SpellingGopher/releases/download/v#{version}/spelling-gopher_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "20176e82fc266b1363ff68df044f1dd14be18fb805ed334639a9bd34724493bc"
      url "https://github.com/Perchinka/SpellingGopher/releases/download/v#{version}/spelling-gopher_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6f6d59114196f94ecf49e9ee09542e2568ff133f6c714933dd713a1c311b7740"
      url "https://github.com/Perchinka/SpellingGopher/releases/download/v#{version}/spelling-gopher_#{version}_linux_arm64.tar.gz"
    end
  end

  name "spelling-gopher"
  desc "A Monkeytype-style terminal typing game"
  homepage "https://github.com/Perchinka/SpellingGopher"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spelling-gopher"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/spelling-gopher"]
    end
  end

  # No zap stanza required

end
