# This file was generated by GoReleaser. DO NOT EDIT.
cask "spelling-gopher" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "92b9177bbd2f840b102101b846b12bca14a9bb3ed43c2bf92d7f10ef1d1370d1"
      url "https://github.com/Perchinka/SpellingGopher/releases/download/v#{version}/spelling-gopher_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6914a92a58fa7c9bb2e54e6ae611f61fc96cd2f4e5e64e5babfdcb90f80cc079"
      url "https://github.com/Perchinka/SpellingGopher/releases/download/v#{version}/spelling-gopher_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "251219bad654a37d891dd37e47be1d23fa02aff3dc1a98a7c254ff91b494cfe4"
      url "https://github.com/Perchinka/SpellingGopher/releases/download/v#{version}/spelling-gopher_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "40aa6839b9b005c069e8a0b56489838c0b93d0557191c30376414c5dca96b10f"
      url "https://github.com/Perchinka/SpellingGopher/releases/download/v#{version}/spelling-gopher_#{version}_linux_arm64.tar.gz"
    end
  end

  name "spelling-gopher"
  desc "A Monkeytype-style terminal typing game"
  homepage "https://github.com/Perchinka/SpellingGopher"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spelling-gopher"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/spelling-gopher"]
    end
  end

  # No zap stanza required

end
