# This file was generated by GoReleaser. DO NOT EDIT.
cask "spelling-gopher" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "d7c0729243224adda0678d612894d8e280e0a48a48aa4c1689c75fe084a1b84c"
      url "https://github.com/Perchinka/SpellingGopher/releases/download/v#{version}/spelling-gopher_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "86031ea11a1ac7b49d1084797e6a0e1dbe8c42505f536e77f07ac150a20b3688"
      url "https://github.com/Perchinka/SpellingGopher/releases/download/v#{version}/spelling-gopher_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "65048f650acbed54095d2bb7ee36d699981387e624552f1ecff60542daefeb7f"
      url "https://github.com/Perchinka/SpellingGopher/releases/download/v#{version}/spelling-gopher_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "87ba5a32eeff9175d87dc2bcf542bfbffca7468a899facf5725ad3a0f8b3a941"
      url "https://github.com/Perchinka/SpellingGopher/releases/download/v#{version}/spelling-gopher_#{version}_linux_arm64.tar.gz"
    end
  end

  name "spelling-gopher"
  desc "A Monkeytype-style terminal typing game"
  homepage "https://github.com/Perchinka/SpellingGopher"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spelling-gopher"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/spelling-gopher"]
    end
  end

  # No zap stanza required

end
